[package]
name = "repo"
version = "0.1.0"
edition = "2021"
authors=["Fuel Labs <contact@fuel.sh>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
