[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "timelock-contract"

[constants]
# TODO: Identity type https://github.com/FuelLabs/sway/issues/2647
MAXIMUM_DELAY = { type = "u64", value = "1000" }
MINIMUM_DELAY = { type = "u64", value = "100" }
OWNER = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }
