[project]
authors = ["ankit"]
entry = "main.sw"
license = "Apache-2.0"
name = "FixedPoint"

[dependencies]
BalancerErrors = { path = "../../helpers/BalancerErrors" }
LogExpMath = { path = "../LogExpMath" }
