[project]
name = "utils"
version = "0.0.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.62.0", features = ["fuel-core-lib"] }

[lib]
test = false
doctest = false
