[project]
name = "node"
version = "0.0.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
utils = { path = "../utils" }
fuels = { version = "0.25", features = ["fuel-core-lib"] }
tokio = { version = "1.12", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.12"
dotenv = "0.15.0"
futures = "0.3"
async-trait = "0.1.58"
anyhow = "1.0.66"
itertools = "0.10.5"

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
