[project]
authors = ["ankit"]
entry = "main.sw"
license = "Apache-2.0"
name = "WeightedMath"

[dependencies]
FixedPoint = { path = "../../../sway-utils/contracts/math/FixedPoint" }
math = { path = "../../../sway-utils/contracts/math/math" }
BalancerErrors = { path = "../../../sway-utils/contracts/helpers/BalancerErrors" }
