[workspace]
members = [
  "./english-auction/project/auction-contract",
  "./english-auction/project/auction-contract/tests/artifacts/asset",
  "./english-auction/project/auction-contract/tests/artifacts/NFT",
  "./dutch-auction"
]
