[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "distributor-contract"

[dependencies]
merkle_proof = { git = "https://github.com/FuelLabs/sway-libs", branch = "ls/feat/std-policies-branch" }
